version: '2'

services:
  web:
    build: .
    command: coffee app.coffee
    volumes:
      - .:/app
    ports:
      - "4066:4000"
    network_mode: bridge
    restart: always

networks:
  default:
    driver: "null"
